### ISSUE TITLE
crash on Kubuntu 20.04

### ISSUE THREAD

**Issue by HieronymusCH** [jeromerobert/k4dirstat#29] opened 2020-05-11 11:32 UTC
K4DirStat crashes everytime as soon as I open the selection windows.

Application: k4dirstat (3.2.0)

Qt Version: 5.12.8
Frameworks Version: 5.68.0
Operating System: Linux 5.4.0-31-generic x86_64
Windowing system: X11
Distribution: Ubuntu 20.04 LTS

-- Information about the crash:
<Erklären Sie bitte ganz genau, was Sie machten, als das Programm abstürzte.>

The crash can be reproduced every time.

-- Backtrace:
Application: k4dirstat (k4dirstat), signal: Segmentation fault
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[Current thread is 1 (Thread 0x7fd44d5e6800 (LWP 780862))]

Thread 7 (Thread 0x7fd441a33700 (LWP 780872)):
#0  futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x55eca5b28558) at ../sysdeps/nptl/futex-internal.h:183
#1  __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x55eca5b28508, cond=0x55eca5b28530) at pthread_cond_wait.c:508
#2  __pthread_cond_wait (cond=0x55eca5b28530, mutex=0x55eca5b28508) at pthread_cond_wait.c:638
#3  0x00007fd44375335b in ?? () from /usr/lib/x86_64-linux-gnu/dri/i965_dri.so
#4  0x00007fd443752f6b in ?? () from /usr/lib/x86_64-linux-gnu/dri/i965_dri.so
#5  0x00007fd44ffda609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#6  0x00007fd4507f5103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 6 (Thread 0x7fd442234700 (LWP 780871)):
#0  futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x55eca5b28558) at ../sysdeps/nptl/futex-internal.h:183
#1  __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x55eca5b28508, cond=0x55eca5b28530) at pthread_cond_wait.c:508
#2  __pthread_cond_wait (cond=0x55eca5b28530, mutex=0x55eca5b28508) at pthread_cond_wait.c:638
#3  0x00007fd44375335b in ?? () from /usr/lib/x86_64-linux-gnu/dri/i965_dri.so
#4  0x00007fd443752f6b in ?? () from /usr/lib/x86_64-linux-gnu/dri/i965_dri.so
#5  0x00007fd44ffda609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#6  0x00007fd4507f5103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 5 (Thread 0x7fd442a35700 (LWP 780870)):
#0  futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x55eca5b28558) at ../sysdeps/nptl/futex-internal.h:183
#1  __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x55eca5b28508, cond=0x55eca5b28530) at pthread_cond_wait.c:508
#2  __pthread_cond_wait (cond=0x55eca5b28530, mutex=0x55eca5b28508) at pthread_cond_wait.c:638
#3  0x00007fd44375335b in ?? () from /usr/lib/x86_64-linux-gnu/dri/i965_dri.so
#4  0x00007fd443752f6b in ?? () from /usr/lib/x86_64-linux-gnu/dri/i965_dri.so
#5  0x00007fd44ffda609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#6  0x00007fd4507f5103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 4 (Thread 0x7fd443236700 (LWP 780869)):
#0  futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x55eca5b28558) at ../sysdeps/nptl/futex-internal.h:183
#1  __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x55eca5b28508, cond=0x55eca5b28530) at pthread_cond_wait.c:508
#2  __pthread_cond_wait (cond=0x55eca5b28530, mutex=0x55eca5b28508) at pthread_cond_wait.c:638
#3  0x00007fd44375335b in ?? () from /usr/lib/x86_64-linux-gnu/dri/i965_dri.so
#4  0x00007fd443752f6b in ?? () from /usr/lib/x86_64-linux-gnu/dri/i965_dri.so
#5  0x00007fd44ffda609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#6  0x00007fd4507f5103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 3 (Thread 0x7fd44ae5a700 (LWP 780864)):
#0  0x00007fd4507e896f in __GI___poll (fds=0x7fd43c01b120, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007fd44f7921ae in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007fd44f7922e3 in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007fd450ed3583 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#4  0x00007fd450e7a4db in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x00007fd450cb2785 in QThread::exec() () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#6  0x00007fd450258efa in ?? () from /lib/x86_64-linux-gnu/libQt5DBus.so.5
#7  0x00007fd450cb39d2 in ?? () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#8  0x00007fd44ffda609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#9  0x00007fd4507f5103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 2 (Thread 0x7fd44c6db700 (LWP 780863)):
#0  0x00007fd4507e896f in __GI___poll (fds=0x7fd44c6daca8, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007fd44f5e2c1a in ?? () from /lib/x86_64-linux-gnu/libxcb.so.1
#2  0x00007fd44f5e490a in xcb_wait_for_event () from /lib/x86_64-linux-gnu/libxcb.so.1
#3  0x00007fd44cec7298 in ?? () from /lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#4  0x00007fd450cb39d2 in ?? () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x00007fd44ffda609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#6  0x00007fd4507f5103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 1 (Thread 0x7fd44d5e6800 (LWP 780862)):
[KCrash Handler]
#6  0x00007fd451607368 in QStandardItem::rowCount() const () from /lib/x86_64-linux-gnu/libQt5Gui.so.5
#7  0x00007fd45160bc74 in QStandardItem::setRowCount(int) () from /lib/x86_64-linux-gnu/libQt5Gui.so.5
#8  0x00007fd45160c113 in ?? () from /lib/x86_64-linux-gnu/libQt5Gui.so.5
#9  0x00007fd45160cc59 in QStandardItemModel::itemFromIndex(QModelIndex const&) const () from /lib/x86_64-linux-gnu/libQt5Gui.so.5
#10 0x000055eca3a7f0fb in KDirSortFilterProxyModel::lessThan(QModelIndex const&, QModelIndex const&) const ()
#11 0x00007fd450e5b462 in ?? () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#12 0x00007fd450e5d94f in ?? () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#13 0x00007fd450e5db79 in ?? () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#14 0x00007fd450e60900 in ?? () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#15 0x00007fd450e50f95 in ?? () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#16 0x00007fd450e55a7f in ?? () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#17 0x00007fd450e590f6 in ?? () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#18 0x00007fd450e59d03 in ?? () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#19 0x00007fd450ea7300 in QMetaObject::activate(QObject*, int, int, void**) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#20 0x00007fd450e27ca2 in QAbstractItemModel::rowsInserted(QModelIndex const&, int, int, QAbstractItemModel::QPrivateSignal) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#21 0x00007fd450e30768 in QAbstractItemModel::endInsertRows() () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#22 0x00007fd45247e4d8 in ?? () from /lib/x86_64-linux-gnu/libKF5KIOWidgets.so.5
#23 0x00007fd450ea7458 in QMetaObject::activate(QObject*, int, int, void**) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#24 0x00007fd45228700e in KCoreDirLister::itemsAdded(QUrl const&, KFileItemList const&) () from /lib/x86_64-linux-gnu/libKF5KIOCore.so.5
#25 0x00007fd4522899b3 in ?? () from /lib/x86_64-linux-gnu/libKF5KIOCore.so.5
#26 0x00007fd45229b638 in ?? () from /lib/x86_64-linux-gnu/libKF5KIOCore.so.5
#27 0x00007fd450ea7458 in QMetaObject::activate(QObject*, int, int, void**) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#28 0x00007fd452232e88 in KIO::ListJob::entries(KIO::Job*, QList<KIO::UDSEntry> const&) () from /lib/x86_64-linux-gnu/libKF5KIOCore.so.5
#29 0x00007fd452234822 in ?? () from /lib/x86_64-linux-gnu/libKF5KIOCore.so.5
#30 0x00007fd450ea7458 in QMetaObject::activate(QObject*, int, int, void**) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#31 0x00007fd45220b7c9 in KIO::SlaveInterface::listEntries(QList<KIO::UDSEntry> const&) () from /lib/x86_64-linux-gnu/libKF5KIOCore.so.5
#32 0x00007fd45220e1b6 in KIO::SlaveInterface::dispatch(int, QByteArray const&) () from /lib/x86_64-linux-gnu/libKF5KIOCore.so.5
#33 0x00007fd45220bf4f in KIO::SlaveInterface::dispatch() () from /lib/x86_64-linux-gnu/libKF5KIOCore.so.5
#34 0x00007fd452215152 in KIO::Slave::gotInput() () from /lib/x86_64-linux-gnu/libKF5KIOCore.so.5
#35 0x00007fd450ea7458 in QMetaObject::activate(QObject*, int, int, void**) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#36 0x00007fd450ea7d5a in QObject::event(QEvent*) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#37 0x00007fd451893a66 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#38 0x00007fd45189d0f0 in QApplication::notify(QObject*, QEvent*) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#39 0x00007fd450e7b93a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#40 0x00007fd450e7e5b8 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#41 0x00007fd450ed3f67 in ?? () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#42 0x00007fd44f791fbd in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#43 0x00007fd44f792240 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#44 0x00007fd44f7922e3 in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#45 0x00007fd450ed3565 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#46 0x00007fd450e7a4db in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#47 0x00007fd451a97c6d in QDialog::exec() () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#48 0x00007fd451a97b71 in QDialog::exec() () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#49 0x00007fd451aababa in QFileDialog::getExistingDirectoryUrl(QWidget*, QString const&, QUrl const&, QFlags<QFileDialog::Option>, QStringList const&) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#50 0x000055eca3a6e6fc in k4dirstat::fileAskOpenDir() ()
#51 0x00007fd450ea7300 in QMetaObject::activate(QObject*, int, int, void**) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#52 0x00007fd45188d3e6 in QAction::triggered(bool) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#53 0x00007fd45188faa2 in QAction::activate(QAction::ActionEvent) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#54 0x00007fd451989e10 in ?? () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#55 0x00007fd45198a035 in QAbstractButton::mouseReleaseEvent(QMouseEvent*) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#56 0x00007fd451a7d5fe in QToolButton::mouseReleaseEvent(QMouseEvent*) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#57 0x00007fd4518d62b6 in QWidget::event(QEvent*) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#58 0x00007fd451a7d6a8 in QToolButton::event(QEvent*) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#59 0x00007fd451893a66 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#60 0x00007fd45189d343 in QApplication::notify(QObject*, QEvent*) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#61 0x00007fd450e7b93a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#62 0x00007fd45189c457 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#63 0x00007fd4518f235d in ?? () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#64 0x00007fd4518f51ec in ?? () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#65 0x00007fd451893a66 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#66 0x00007fd45189d0f0 in QApplication::notify(QObject*, QEvent*) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#67 0x00007fd450e7b93a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#68 0x00007fd4512647d3 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () from /lib/x86_64-linux-gnu/libQt5Gui.so.5
#69 0x00007fd45126610b in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () from /lib/x86_64-linux-gnu/libQt5Gui.so.5
#70 0x00007fd45124035b in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /lib/x86_64-linux-gnu/libQt5Gui.so.5
#71 0x00007fd44cec832e in ?? () from /lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#72 0x00007fd44f791fbd in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#73 0x00007fd44f792240 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#74 0x00007fd44f7922e3 in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#75 0x00007fd450ed3565 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#76 0x00007fd450e7a4db in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#77 0x00007fd450e82246 in QCoreApplication::exec() () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#78 0x000055eca3a669a6 in main ()
[Inferior 1 (process 780862) detached]

An https://github.com/jeromerobert/k4dirstat/issues berichten

**Comment by jeromerobert** [comment] 2020-05-13 08:00
Duplicate of #28. Please switch to k4dirstat 3.2.1. I may do a PPA upload if you need.

**Closed** 2020-05-13 08:00 UTC
